# Generated by Django 5.2.1 on 2025-05-20 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meu_app', '0001_initial'),
    ]

    operations = [
    ]
